# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "85fe93aad9b98031fdfa87adaca89100"
name = "beautiful-consent-app"
application_url = "https://pulled-votes-andrew-district.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mot-marioo-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://pulled-votes-andrew-district.trycloudflare.com/auth/callback",
  "https://pulled-votes-andrew-district.trycloudflare.com/auth/shopify/callback",
  "https://pulled-votes-andrew-district.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
