# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a73ff523739143bad873779b2ebc47d4"
name = "beatiful-consent"
application_url = "https://occupational-ur-oxygen-circles.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mot-vcg-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://occupational-ur-oxygen-circles.trycloudflare.com/auth/callback",
  "https://occupational-ur-oxygen-circles.trycloudflare.com/auth/shopify/callback",
  "https://occupational-ur-oxygen-circles.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
