# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2049265785ee965761bad77c3f6d6e7b"
name = "Beautiful Consent"
application_url = "https://dated-shoot-comics-logan.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mot-marioo-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://dated-shoot-comics-logan.trycloudflare.com/auth/callback",
  "https://dated-shoot-comics-logan.trycloudflare.com/auth/shopify/callback",
  "https://dated-shoot-comics-logan.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
