# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a31c3006263c3213da34f87e764b9562"
name = "beautiful-consent"
application_url = "https://israel-img-internet-convenient.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mot-marioo-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://israel-img-internet-convenient.trycloudflare.com/auth/callback",
  "https://israel-img-internet-convenient.trycloudflare.com/auth/shopify/callback",
  "https://israel-img-internet-convenient.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
